name: update-docs
<<<<<<< HEAD
on:
  release:
    types: [created]
=======
on: [push]
>>>>>>> 5729caf (refactor(global): some code refactoring, added default export, docs updated by gh actions only now)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
<<<<<<< HEAD
      - run: npm ci
      - run: |
          npm run build
          npm run docs
          npm run format
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Updated documentation" -a
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
=======
      - name: Generate docs
      - run: npm ci
      - run: npm run build
      - run: npm run docs
      - run: npm run format
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updated documentation" -a
      - name: Push docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 5729caf (refactor(global): some code refactoring, added default export, docs updated by gh actions only now)
          branch: ${{ github.ref }}
